# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import market_demo_pb2 as market__demo__pb2


class DataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubscribeData = channel.unary_stream(
                '/DataService/SubscribeData',
                request_serializer=market__demo__pb2.DataRequest.SerializeToString,
                response_deserializer=market__demo__pb2.DataResponse.FromString,
                )
        self.TestClietSendStream = channel.stream_unary(
                '/DataService/TestClietSendStream',
                request_serializer=market__demo__pb2.StreamRequest.SerializeToString,
                response_deserializer=market__demo__pb2.StreamResponse.FromString,
                )
        self.TwoWayStream = channel.stream_stream(
                '/DataService/TwoWayStream',
                request_serializer=market__demo__pb2.TwoWayStreamRequest.SerializeToString,
                response_deserializer=market__demo__pb2.TwoWayStreamResponse.FromString,
                )


class DataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubscribeData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestClietSendStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TwoWayStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubscribeData': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeData,
                    request_deserializer=market__demo__pb2.DataRequest.FromString,
                    response_serializer=market__demo__pb2.DataResponse.SerializeToString,
            ),
            'TestClietSendStream': grpc.stream_unary_rpc_method_handler(
                    servicer.TestClietSendStream,
                    request_deserializer=market__demo__pb2.StreamRequest.FromString,
                    response_serializer=market__demo__pb2.StreamResponse.SerializeToString,
            ),
            'TwoWayStream': grpc.stream_stream_rpc_method_handler(
                    servicer.TwoWayStream,
                    request_deserializer=market__demo__pb2.TwoWayStreamRequest.FromString,
                    response_serializer=market__demo__pb2.TwoWayStreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubscribeData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/DataService/SubscribeData',
            market__demo__pb2.DataRequest.SerializeToString,
            market__demo__pb2.DataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TestClietSendStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/DataService/TestClietSendStream',
            market__demo__pb2.StreamRequest.SerializeToString,
            market__demo__pb2.StreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TwoWayStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/DataService/TwoWayStream',
            market__demo__pb2.TwoWayStreamRequest.SerializeToString,
            market__demo__pb2.TwoWayStreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
