# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account_position.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x61\x63\x63ount_position.proto\x12\x10\x61\x63\x63ount_position\x1a\x1fgoogle/protobuf/timestamp.proto\"\xca\x01\n\x0b\x41\x63\x63ountBook\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12-\n\tpositions\x18\x02 \x03(\x0b\x32\x1a.account_position.Position\x12:\n\x10instrument_books\x18\x03 \x03(\x0b\x32 .account_position.InstrumentBook\x12\r\n\x05\x61vail\x18\x04 \x01(\x01\x12-\n\tcreate_ts\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xcf\x01\n\x08Position\x12\x11\n\tdirection\x18\x01 \x01(\t\x12\x12\n\ninstrument\x18\x02 \x01(\t\x12\x0b\n\x03\x61vg\x18\x03 \x01(\x01\x12\x0e\n\x06volume\x18\x04 \x01(\x01\x12\n\n\x02yd\x18\x05 \x01(\x01\x12\x0e\n\x06locked\x18\x06 \x01(\x01\x12\x0f\n\x07\x64\x65\x66\x61ult\x18\x07 \x01(\x08\x12\x0e\n\x06margin\x18\x08 \x01(\x01\x12\x0c\n\x04\x63ost\x18\t \x01(\x01\x12\x10\n\x08open_avg\x18\n \x01(\x01\x12\x10\n\x08\x65xchange\x18\x0b \x01(\t\x12\x10\n\x08sellable\x18\x0c \x01(\x01\"\xa3\x01\n\x0eInstrumentBook\x12\x12\n\ninstrument\x18\x01 \x01(\t\x12\x1b\n\x13\x63ontract_multiplier\x18\x02 \x01(\x01\x12\x19\n\x11long_margin_ratio\x18\x03 \x01(\x01\x12\x1a\n\x12short_margin_ratio\x18\x04 \x01(\x01\x12\x12\n\nprice_tick\x18\x05 \x01(\x01\x12\x15\n\rproduct_class\x18\x06 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'account_position_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACCOUNTBOOK._serialized_start=78
  _ACCOUNTBOOK._serialized_end=280
  _POSITION._serialized_start=283
  _POSITION._serialized_end=490
  _INSTRUMENTBOOK._serialized_start=493
  _INSTRUMENTBOOK._serialized_end=656
# @@protoc_insertion_point(module_scope)
