# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: market_server.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13market_server.proto\"\x1a\n\x07Symbols\x12\x0f\n\x07symbols\x18\x01 \x03(\t\"W\n\x05Quote\x12 \n\x05quote\x18\x01 \x03(\x0b\x32\x11.Quote.QuoteEntry\x1a,\n\nQuoteEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x19\n\tFlagReply\x12\x0c\n\x04\x66lag\x18\x01 \x01(\x08\x32\x85\x01\n\x11\x41syncMarketServer\x12$\n\x0eGetQuoteStream\x12\x08.Symbols\x1a\x06.Quote0\x01\x12$\n\x0c\x41\x64\x64Subscribe\x12\x08.Symbols\x1a\n.FlagReply\x12$\n\nStopEngine\x12\n.FlagReply\x1a\n.FlagReplyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'market_server_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _QUOTE_QUOTEENTRY._options = None
  _QUOTE_QUOTEENTRY._serialized_options = b'8\001'
  _SYMBOLS._serialized_start=23
  _SYMBOLS._serialized_end=49
  _QUOTE._serialized_start=51
  _QUOTE._serialized_end=138
  _QUOTE_QUOTEENTRY._serialized_start=94
  _QUOTE_QUOTEENTRY._serialized_end=138
  _FLAGREPLY._serialized_start=140
  _FLAGREPLY._serialized_end=165
  _ASYNCMARKETSERVER._serialized_start=168
  _ASYNCMARKETSERVER._serialized_end=301
# @@protoc_insertion_point(module_scope)
