# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trade_server.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from a_songbo.vn.proto import account_position_pb2 as account__position__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12trade_server.proto\x12\x0ctrade_server\x1a\x16\x61\x63\x63ount_position.proto\"\'\n\x11SubAccountRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\"_\n\x15GetAccountBookRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x13\n\x0binstruments\x18\x02 \x03(\t\x12\x1d\n\x15need_instrument_books\x18\x03 \x01(\x08\"\xe0\x01\n\x12InsertOrderRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x12\n\ninstrument\x18\x02 \x01(\t\x12\x15\n\rexchange_type\x18\x03 \x01(\t\x12\x13\n\x0boffset_flag\x18\x04 \x01(\t\x12\x11\n\tdirection\x18\x05 \x01(\t\x12\x18\n\x10order_price_type\x18\x06 \x01(\t\x12\r\n\x05price\x18\x07 \x01(\t\x12\x0e\n\x06volume\x18\x08 \x01(\t\x12\x13\n\x0bsource_type\x18\t \x01(\t\x12\x15\n\rorder_info_id\x18\n \x01(\t\"K\n\x10InsertOrderReply\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x12\n\nerror_code\x18\x02 \x01(\t\x12\x11\n\terror_msg\x18\x03 \x01(\t\":\n\x12\x43\x61ncelOrderRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x10\n\x08order_id\x18\x02 \x01(\t\"L\n\x10\x43\x61ncelOrderReply\x12\x11\n\taction_id\x18\x01 \x01(\t\x12\x12\n\nerror_code\x18\x02 \x01(\t\x12\x11\n\terror_msg\x18\x03 \x01(\t2\xd2\x02\n\x05Trade\x12M\n\x0bsub_account\x12\x1f.trade_server.SubAccountRequest\x1a\x1d.account_position.AccountBook\x12V\n\x10get_account_book\x12#.trade_server.GetAccountBookRequest\x1a\x1d.account_position.AccountBook\x12P\n\x0cinsert_order\x12 .trade_server.InsertOrderRequest\x1a\x1e.trade_server.InsertOrderReply\x12P\n\x0c\x63\x61ncel_order\x12 .trade_server.CancelOrderRequest\x1a\x1e.trade_server.CancelOrderReplyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trade_server_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SUBACCOUNTREQUEST._serialized_start=60
  _SUBACCOUNTREQUEST._serialized_end=99
  _GETACCOUNTBOOKREQUEST._serialized_start=101
  _GETACCOUNTBOOKREQUEST._serialized_end=196
  _INSERTORDERREQUEST._serialized_start=199
  _INSERTORDERREQUEST._serialized_end=423
  _INSERTORDERREPLY._serialized_start=425
  _INSERTORDERREPLY._serialized_end=500
  _CANCELORDERREQUEST._serialized_start=502
  _CANCELORDERREQUEST._serialized_end=560
  _CANCELORDERREPLY._serialized_start=562
  _CANCELORDERREPLY._serialized_end=638
  _TRADE._serialized_start=641
  _TRADE._serialized_end=979
# @@protoc_insertion_point(module_scope)
