# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stream_data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11stream_data.proto\"\x18\n\x08Requests\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\x17\n\x05Reply\x12\x0e\n\x06result\x18\x01 \x01(\t2\xaf\x01\n\tStreamRpc\x12$\n\x0fGetServerResult\x12\t.Requests\x1a\x06.Reply\x12&\n\x0fGetServerStream\x12\t.Requests\x1a\x06.Reply0\x01\x12\'\n\x10\x43lientSendStream\x12\t.Requests\x1a\x06.Reply(\x01\x12+\n\x12ServerClientStream\x12\t.Requests\x1a\x06.Reply(\x01\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stream_data_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUESTS._serialized_start=21
  _REQUESTS._serialized_end=45
  _REPLY._serialized_start=47
  _REPLY._serialized_end=70
  _STREAMRPC._serialized_start=73
  _STREAMRPC._serialized_end=248
# @@protoc_insertion_point(module_scope)
